export const ON_CAPITAL_NAME_SUBMIT = 'country/ON_CAPITAL_NAME_SUBMIT';
export const FETCH_COUNTRY_SUCCESS = 'country/FETCH_COUNTRY_SUCCESS';
export const CHANGE_SELECTED_COUNTRY = 'country/CHANGE_SELECTED_COUNTRY';
export const REMOVE_COUNTRY = 'country/REMOVE_COUNTRY';
